namespace CarinaStudio.ULogViewer.Logs.DataSources;

/// <summary>
/// Message generated by <see cref="ILogDataSource"/>.
/// </summary>
class LogDataSourceMessage
{
    /// <summary>
    /// Initialize new <see cref="LogDataSourceMessage"/> instance.
    /// </summary>
    /// <param name="type">Type.</param>
    /// <param name="message">Message.</param>
    public LogDataSourceMessage(LogDataSourceMessageType type, string message)
    {
        this.Message = message;
        this.Type = type;
    }


    /// <summary>
    /// Get message.
    /// </summary>
    public string Message { get; }


    /// <inheritdoc/>
    public override string ToString() =>
        this.Message;


    /// <summary>
    /// Get type of message.
    /// </summary>
    public LogDataSourceMessageType Type { get; }
}


/// <summary>
/// Type of message generated by <see cref="ILogDataSource"/>.
/// </summary>
enum LogDataSourceMessageType
{
    /// <summary>
    /// Information.
    /// </summary>
    Information,
    /// <summary>
    /// Warning.
    /// </summary>
    Warning,
    /// <summary>
    /// Error.
    /// </summary>
    Error,
}